export const CONNECTION_STATUS_CHANGED = 'CONNECTION_STATUS_CHANGED';
export const CONNECTION_KEY_RECEIVED = 'CONNECTION_KEY_RECEIVED';
export const SESSION_STATUS_CHANGED = 'SESSION_STATUS_CHANGED';
