export const RECEIVED_CLIPBOARD = 'RECEIVED_CLIPBOARD';
export const CLEAR_CLIPBOARDS = 'CLEAR_CLIPBOARDS';

export const ADDED_CLIPBOARD_TO_QUEUE = 'ADDED_CLIPBOARD_TO_QUEUE';
export const REMOVED_CLIPBOARD_TO_QUEUE = 'REMOVED_CLIPBOARD_TO_QUEUE';
